/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */
package com.augmate.sdk.voice;

public final class R {
	public static final class anim {
		public static final int animator = 0x7f040000;
		public static final int animator_set = 0x7f040001;
		public static final int color_animator = 0x7f040002;
		public static final int cycle_7 = 0x7f040003;
		public static final int fade = 0x7f040004;
		public static final int grow_then_fade = 0x7f040005;
		public static final int hide_contextual = 0x7f040006;
		public static final int hold = 0x7f040007;
		public static final int hyperspace_in = 0x7f040008;
		public static final int hyperspace_out = 0x7f040009;
		public static final int layout_animation_row_left_slide = 0x7f04000a;
		public static final int layout_animation_row_right_slide = 0x7f04000b;
		public static final int layout_animation_table = 0x7f04000c;
		public static final int layout_bottom_to_top_slide = 0x7f04000d;
		public static final int layout_grid_fade = 0x7f04000e;
		public static final int layout_grid_inverse_fade = 0x7f04000f;
		public static final int layout_random_fade = 0x7f040010;
		public static final int layout_wave_scale = 0x7f040011;
		public static final int object_animator = 0x7f040012;
		public static final int pulse = 0x7f040013;
		public static final int push_left_in = 0x7f040014;
		public static final int push_left_out = 0x7f040015;
		public static final int push_up_in = 0x7f040016;
		public static final int push_up_out = 0x7f040017;
		public static final int shake = 0x7f040018;
		public static final int show_contextual = 0x7f040019;
		public static final int slide_left = 0x7f04001b;
		public static final int slide_right = 0x7f04001d;
		public static final int slide_top_to_bottom = 0x7f04001e;
		public static final int wave_scale = 0x7f04001f;
		public static final int zoom_enter = 0x7f040020;
		public static final int zoom_exit = 0x7f040021;
	}
	public static final class dimen {
		public static final int background_dim_amount = 0x7f080002;
		public static final int large_text_size = 0x7f080004;
		public static final int medium_text_size = 0x7f080006;
		public static final int slider_bar_height = 0x7f080008;
		public static final int small_text_size = 0x7f08000a;
		public static final int text_padding = 0x7f08000b;
	}
	public static final class drawable {
		public static final int augmate_logo = 0x7f020000;
		public static final int augmate_logo_blue = 0x7f020001;
		public static final int augmate_logo_blue_solid = 0x7f020002;
		public static final int augmate_logo_blue_trans = 0x7f020003;
		public static final int augmate_logo_green = 0x7f020004;
		public static final int augmate_logo_green_solid = 0x7f020005;
		public static final int augmate_logo_green_trans = 0x7f020006;
		public static final int augmate_logo_red = 0x7f020007;
		public static final int augmate_logo_red_solid = 0x7f020008;
		public static final int augmate_logo_red_trans = 0x7f020009;
		public static final int augmate_logo_solid = 0x7f02000a;
		public static final int augmate_logo_trans = 0x7f02000b;
		public static final int bar_candy0001 = 0x7f02000c;
		public static final int bar_candy0002 = 0x7f02000d;
		public static final int bar_candy0003 = 0x7f02000e;
		public static final int bar_candy0004 = 0x7f02000f;
		public static final int bar_candy0005 = 0x7f020010;
		public static final int bar_candy0006 = 0x7f020011;
		public static final int bar_candy0007 = 0x7f020012;
		public static final int bar_candy0008 = 0x7f020013;
		public static final int bar_candy0009 = 0x7f020014;
		public static final int bar_candy0010 = 0x7f020015;
		public static final int bar_candy0011 = 0x7f020016;
		public static final int bar_candy0012 = 0x7f020017;
		public static final int bar_candy0013 = 0x7f020018;
		public static final int bar_candy0014 = 0x7f020019;
		public static final int bar_candy0015 = 0x7f02001a;
		public static final int bar_candy0016 = 0x7f02001b;
		public static final int bar_candy0017 = 0x7f02001c;
		public static final int bar_candy0018 = 0x7f02001d;
		public static final int bar_candy0019 = 0x7f02001e;
		public static final int bar_candy0020 = 0x7f02001f;
		public static final int bar_candy0021 = 0x7f020020;
		public static final int bar_candy0022 = 0x7f020021;
		public static final int bar_candy0023 = 0x7f020022;
		public static final int bar_candy0024 = 0x7f020023;
		public static final int bar_candy0025 = 0x7f020024;
		public static final int bar_candy0026 = 0x7f020025;
		public static final int bar_candy0027 = 0x7f020026;
		public static final int bar_candy0028 = 0x7f020027;
		public static final int bar_candy0029 = 0x7f020028;
		public static final int bar_candy0030 = 0x7f020029;
		public static final int error_icon = 0x7f02002b;
		public static final int ic_launcher = 0x7f02002e;
		public static final int pulse_circle = 0x7f020030;
		public static final int pulse_circle_filled = 0x7f020031;
		public static final int slider_indeterminate = 0x7f020032;
	}
	public static final class id {
		public static final int body = 0x7f090011;
		public static final int imageView = 0x7f090013;
		public static final int imageView2 = 0x7f090012;
		public static final int imageView3 = 0x7f090017;
		public static final int indeterm_slider = 0x7f090016;
		public static final int indeterminate_slider = 0x7f090002;
		public static final int prompt_field = 0x7f090014;
		public static final int results_field = 0x7f090015;
		public static final int slider_control = 0x7f090004;
	}
	public static final class integer {
		public static final int activity_animation_duration_ms = 0x7f0a0000;
		public static final int horizontal_scroll_deferred_load_animation_duration_ms = 0x7f0a0001;
		public static final int horizontal_scroll_deferred_sizing_animation_duration_ms = 0x7f0a0002;
		public static final int infos_error_duration_ms = 0x7f0a0003;
		public static final int infos_success_duration_ms = 0x7f0a0004;
		public static final int sys_storage_threshold_bytes = 0x7f0a0005;
		public static final int sys_storage_threshold_percentage = 0x7f0a0006;
	}
	public static final class layout {
		public static final int activity_main = 0x7f030003;
		public static final int slider = 0x7f03000e;
		public static final int voice_capture = 0x7f03000f;
	}
	public static final class raw {
		public static final int correct_sound = 0x7f060000;
		public static final int start_sound = 0x7f060001;
		public static final int wrong_sound = 0x7f060002;
	}
	public static final class string {
		public static final int app_name = 0x7f0b0003;
		public static final int augmate_logo = 0x7f0b0004;
		public static final int hello_world = 0x7f0b0009;
		public static final int voice_sample_activity = 0x7f0b0015;
	}
	public static final class style {
		public static final int ContextualDialog = 0x7f0c0001;
		public static final int ContextualDialogTheme = 0x7f0c0002;
		public static final int ContextualDialogTheme_NoAnimation = 0x7f0c0003;
		public static final int LargeOverlayText = 0x7f0c0004;
		public static final int MediumOverlayText = 0x7f0c0005;
		public static final int OverlayText = 0x7f0c0006;
		public static final int SmallOverlayText = 0x7f0c0007;
	}
}
